apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/cosminmusat/ci_cd_lab@sha256:8f4e514dfcb33a88212b64e5ed8d5d80bfaca0f02153c68066ac8aa686fe161e
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
